### PR TITLE
when outputting compat makefile, depend on inputs too; add appropriate test

### PR DESCRIPTION
**Pull request by sinelaw**

### CODE REVIEW

**Comment by sinelaw** [comment]
don't merge this yet - for some reason it seems to omit certain targets

**Comment by sinelaw** [comment]
Much better now, you can merge.
However there is still an outstanding issue - see the expected makefile - it doesn't specify "foo.c" as an input for "moshe.a" and "moshe.a.b" even though the command to create them opens and reads from that file.

**Comment by sinelaw** [comment]
Fixed the issue mentioned above, you can merge

**Comment by sinelaw** [comment]
MERGE MEEEEEEEEeeeee

**Comment by sinelaw** [comment]
Updated and fixed CR stuff. Ready for merge :)

**Comment by sinelaw** [comment]
Updated and fixed CR stuff. Ready for merge :)

**Comment by ElastiLotem** [comment]
There's a lot of "code churn" in the PR -- adding stuff, changing their indent/spacing later..
Or the addition of the existingInputs and then removing it..

Can you change this branch to add only the final version of stuff?

**Comment by sinelaw** [comment]
Fixed CR comments - merge ready!

**Comment by sinelaw** [comment]
(some of the fixes were squashed into commiits, others collected in "CR fixes" commit)

**Comment by sinelaw** [comment]
updated (yet again) - fixed the target inputs issues and cleaned up some stuff you commented on

**Comment by sinelaw** [comment]
P.S. I didn't add the switch on whether or not to calculate the extra inputs, it needs to be passed from  Main. You're welcome to do it! :) 
(plus the extra squashing you wanted)

**Comment by ElastiLotem** [comment]
Merged

**Comment by sinelaw** [comment]
Thanks!

**Pull request closed without merging**
