### PR TITLE
fs_override: when asserting, print also to stderr (we're going to abort anyway)

### PR DESCRIPTION
**Pull request by sinelaw**
Normally we only print to the obscure log file.
When failing assert there's not problem to pollute stderr, because we're going to abort the process anyway.

### CODE REVIEW

**Comment by ElastiLotem** [comment]
This isn't needed. https://github.com/ElastiLotem/buildsome/commit/d1793bbfc33d021daeb1acf3b0b31703e7ea50bb already prints asserts correctly without assuming stderr is valid.

**Comment by sinelaw** [comment]
Looked at that commit - how does it solve it?

**Comment by sinelaw** [comment]
See here: https://github.com/ElastiLotem/buildsome/blob/master/cbits/c.h#L15
Asserts just fprintf to log_file() and abort immediately

**Comment by Peaker** [comment]
Oops I meant https://github.com/ElastiLotem/buildsome/commit/54e75288f2de30ad0d54d3293d9b305dcca48f0a

But indeed it might not be hooked to assert.

Better hook that somehow and not stderr.

**Comment by ElastiLotem** [comment]
https://github.com/ElastiLotem/buildsome/commit/46168ab51bc9c734606c31bb2a4982740df2bcbf
Now handles it well.

**Pull request closed without merging**
